services:
  natroutter.fi:
    container_name: NATroutter.fi
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - TURNSTILE_SECRET=change_me
      - TURNSTILE_SITEKEY=change_me
    ports:
      - 127.0.0.1:8500:3000
      #- 8400:3000