services:
  natroutter-fi-frontend:
    hostname: natroutter-fi-frontend
    container_name: natroutter-fi-frontend
    restart: always
    build:
      context: https://github.com/NATroutter/natroutter.fi.git#master
      additional_contexts:
        - app=docker-image://natroutter-fi-frontend:latest
      args:
        MAL_CLIENT_ID: change_me
    ports:
      - 8510:3000