services:
  natroutter-fi-frontend:
    hostname: natroutter-fi-frontend
    container_name: natroutter-fi-frontend
    restart: always
    build:
      context: .
      additional_contexts:
        - app=docker-image://natroutter-fi-frontend:latest
    ports:
      - 8510:3000
      #- 127.0.0.1:8510:3000
    environment:
      MAL_CLIENT_ID: change_me
      POCKETBASE_ADDRESS: change_me
      UMAMI_SCRIPT: change_me
      UMAMI_TOKEN: change_me
