import type { Metadata } from "next";
import "@/styles/globals.css";
import * as React from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {getFooterData, getNavigatorData} from "@/lib/database";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    const NavData = await getNavigatorData();
    const footerData = await getFooterData();

    return (
        <html lang="en">
            <body className="flex flex-col min-h-screen overflow-y-auto">

            <Header data={NavData}/>

            <main className="flex flex-col flex-grow mt-[7.5rem]">
            {   children}
            </main>

            <Footer data={footerData}/>

            </body>
        </html>
    );
}
