"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _home_page from './home-page.bones.json'
import _about_page from './about-page.bones.json'
import _projects_page from './projects-page.bones.json'
import _links_page from './links-page.bones.json'
import _privacy_page from './privacy-page.bones.json'
import _anime_stats_page from './anime-stats-page.bones.json'
import _anime_list_page from './anime-list-page.bones.json'
import _anime_favorites_page from './anime-favorites-page.bones.json'
import _site_footer from './site-footer.bones.json'

configureBoneyard({"color":"hsl(var(--muted))","darkColor":"hsl(var(--muted))","animate":"shimmer","stagger":40,"transition":200})

registerBones({
  "home-page": _home_page,
  "about-page": _about_page,
  "projects-page": _projects_page,
  "links-page": _links_page,
  "privacy-page": _privacy_page,
  "anime-stats-page": _anime_stats_page,
  "anime-list-page": _anime_list_page,
  "anime-favorites-page": _anime_favorites_page,
  "site-footer": _site_footer,
})
